const uiText = {
  es: {
    title: "Calculadora de Matemáticas Financieras",
    subtitle:
      "Practica fórmulas de interés simple, valor presente, valor futuro y descuento comercial.",
    formulaLabel: "Elige una fórmula",
    calculate: "Calcular",
    clear: "Limpiar",
    resultTitle: "Resultado",
    footerNote:
      "Esta herramienta es solo para fines educativos y utiliza interés simple.",
    errors: {
      required: "Por favor completa todos los campos.",
      invalidNumber: "Revisa que todos los valores numéricos sean válidos.",
      negativeEffective:
        "La combinación de tasa y periodos hace que el valor efectivo sea negativo.",
    },
  },
  en: {
    title: "Financial Mathematics Calculator",
    subtitle:
      "Practice simple-interest formulas for present value, future value, and commercial discount.",
    formulaLabel: "Choose a formula",
    calculate: "Calculate",
    clear: "Clear",
    resultTitle: "Result",
    footerNote:
      "This tool is for educational purposes only and uses simple interest.",
    errors: {
      required: "Please fill in all fields.",
      invalidNumber: "Make sure all numeric values are valid.",
      negativeEffective:
        "The combination of rate and periods makes the effective value negative.",
    },
  },
};

const formulas = {
  future_value_simple: {
    id: "future_value_simple",
    symbol: "Vf = Vp (1 + i n)",
    names: {
      es: "Valor futuro (interés simple)",
      en: "Future value (simple interest)",
    },
    description: {
      es: "Calcula el valor futuro de una inversión con interés simple.",
      en: "Computes the future value of an investment under simple interest.",
    },
    resultSymbol: "Vf",
    inputs: [
      {
        id: "Vp",
        type: "amount",
        labels: { es: "Valor presente Vp", en: "Present value Vp" },
        placeholder: { es: "Cantidad inicial", en: "Initial amount" },
      },
      {
        id: "i",
        type: "rate",
        labels: {
          es: "Tasa simple por periodo i (%)",
          en: "Simple rate per period i (%)",
        },
        placeholder: { es: "Porcentaje por periodo", en: "Percent per period" },
      },
      {
        id: "n",
        type: "periods",
        labels: { es: "Número de periodos n", en: "Number of periods n" },
        placeholder: { es: "Meses, años, etc.", en: "Months, years, etc." },
      },
    ],
    compute: ({ Vp, i, n }) => Vp * (1 + i * n),
  },
  present_value_simple: {
    id: "present_value_simple",
    symbol: "Vp = Vf / (1 + i n)",
    names: {
      es: "Valor presente (interés simple)",
      en: "Present value (simple interest)",
    },
    description: {
      es: "Calcula el valor presente equivalente de un monto futuro con interés simple.",
      en: "Computes the present value equivalent of a future amount under simple interest.",
    },
    resultSymbol: "Vp",
    inputs: [
      {
        id: "Vf",
        type: "amount",
        labels: { es: "Valor futuro Vf", en: "Future value Vf" },
        placeholder: { es: "Monto futuro", en: "Future amount" },
      },
      {
        id: "i",
        type: "rate",
        labels: {
          es: "Tasa simple por periodo i (%)",
          en: "Simple rate per period i (%)",
        },
        placeholder: { es: "Porcentaje por periodo", en: "Percent per period" },
      },
      {
        id: "n",
        type: "periods",
        labels: { es: "Número de periodos n", en: "Number of periods n" },
        placeholder: { es: "Meses, años, etc.", en: "Months, years, etc." },
      },
    ],
    compute: ({ Vf, i, n }) => Vf / (1 + i * n),
  },
  simple_interest: {
    id: "simple_interest",
    symbol: "I = Vf - Vp",
    names: {
      es: "Interés simple generado",
      en: "Simple interest earned",
    },
    description: {
      es: "Calcula el interés simple generado por una inversión.",
      en: "Calculates the simple interest generated by an investment.",
    },
    resultSymbol: "I",
    inputs: [
      {
        id: "Vf",
        type: "amount",
        labels: { es: "Valor futuro Vf", en: "Future value Vf" },
        placeholder: { es: "Monto futuro", en: "Future amount" },
      },
      {
        id: "Vp",
        type: "amount",
        labels: { es: "Valor presente Vp", en: "Present value Vp" },
        placeholder: { es: "Monto inicial", en: "Initial amount" },
      },
    ],
    compute: ({ Vf, Vp }) => Vf - Vp,
  },
  simple_rate: {
    id: "simple_rate",
    symbol: "i = (Vf / Vp − 1) / n",
    names: {
      es: "Tasa de interés simple",
      en: "Simple interest rate",
    },
    description: {
      es: "Obtiene la tasa de interés simple a partir del valor presente y futuro.",
      en: "Finds the simple interest rate from present and future values.",
    },
    resultSymbol: "i",
    resultIsRate: true,
    inputs: [
      {
        id: "Vf",
        type: "amount",
        labels: { es: "Valor futuro Vf", en: "Future value Vf" },
        placeholder: { es: "Monto futuro", en: "Future amount" },
      },
      {
        id: "Vp",
        type: "amount",
        labels: { es: "Valor presente Vp", en: "Present value Vp" },
        placeholder: { es: "Monto inicial", en: "Initial amount" },
      },
      {
        id: "n",
        type: "periods",
        labels: { es: "Número de periodos n", en: "Number of periods n" },
        placeholder: { es: "Meses, años, etc.", en: "Months, years, etc." },
      },
    ],
    compute: ({ Vf, Vp, n }) => (Vf / Vp - 1) / n,
  },
  commercial_discount: {
    id: "commercial_discount",
    symbol: "D = Vf d n",
    names: {
      es: "Descuento comercial D",
      en: "Commercial discount D",
    },
    description: {
      es: "Calcula el descuento comercial aplicado a un valor futuro.",
      en: "Computes the commercial discount applied to a future value.",
    },
    resultSymbol: "D",
    inputs: [
      {
        id: "Vf",
        type: "amount",
        labels: { es: "Valor futuro Vf", en: "Future value Vf" },
        placeholder: { es: "Monto futuro", en: "Future amount" },
      },
      {
        id: "d",
        type: "rate",
        labels: {
          es: "Tasa de descuento d (%)",
          en: "Discount rate d (%)",
        },
        placeholder: {
          es: "Porcentaje de descuento",
          en: "Discount percentage",
        },
      },
      {
        id: "n",
        type: "periods",
        labels: { es: "Número de periodos n", en: "Number of periods n" },
        placeholder: { es: "Meses, años, etc.", en: "Months, years, etc." },
      },
    ],
    compute: ({ Vf, d, n }) => Vf * d * n,
  },
  effective_value: {
    id: "effective_value",
    symbol: "VE = Vf (1 − d n)",
    names: {
      es: "Valor efectivo VE",
      en: "Effective value VE",
    },
    description: {
      es: "Calcula el valor efectivo después del descuento comercial.",
      en: "Computes the effective value after commercial discount.",
    },
    resultSymbol: "VE",
    inputs: [
      {
        id: "Vf",
        type: "amount",
        labels: { es: "Valor futuro Vf", en: "Future value Vf" },
        placeholder: { es: "Monto futuro", en: "Future amount" },
      },
      {
        id: "d",
        type: "rate",
        labels: {
          es: "Tasa de descuento d (%)",
          en: "Discount rate d (%)",
        },
        placeholder: {
          es: "Porcentaje de descuento",
          en: "Discount percentage",
        },
      },
      {
        id: "n",
        type: "periods",
        labels: { es: "Número de periodos n", en: "Number of periods n" },
        placeholder: { es: "Meses, años, etc.", en: "Months, years, etc." },
      },
    ],
    compute: ({ Vf, d, n }) => Vf * (1 - d * n),
    validate: ({ d, n }) => 1 - d * n >= 0,
  },
  period_rate_from_annual: {
    id: "period_rate_from_annual",
    symbol: "i = i_an / n",
    names: {
      es: "Tasa por periodo desde tasa anual",
      en: "Per-period rate from annual rate",
    },
    description: {
      es: "Convierte una tasa anual nominal en la tasa simple por periodo.",
      en: "Converts a nominal annual rate into a simple rate per period.",
    },
    resultSymbol: "i",
    resultIsRate: true,
    inputs: [
      {
        id: "ian",
        type: "rate",
        labels: {
          es: "Tasa anual nominal i_an (%)",
          en: "Annual nominal rate i_an (%)",
        },
        placeholder: {
          es: "Porcentaje anual",
          en: "Annual percentage",
        },
      },
      {
        id: "n",
        type: "periods",
        labels: {
          es: "Número de periodos por año n",
          en: "Number of periods per year n",
        },
        placeholder: { es: "Por ejemplo 12", en: "For example 12" },
      },
    ],
    compute: ({ ian, n }) => ian / n,
  },
};

let currentLang = "es";
let currentPeriodMode = "monthly"; // "monthly" | "yearly"
const MONTHS_PER_YEAR = 12;

function getNumberValue(raw) {
  const value = parseFloat(String(raw).replace(",", "."));
  return Number.isFinite(value) ? value : NaN;
}

function formatCurrency(amount, lang) {
  if (!Number.isFinite(amount)) return "—";
  const locale = lang === "es" ? "es-MX" : "en-US";
  return new Intl.NumberFormat(locale, {
    style: "currency",
    currency: "MXN",
    maximumFractionDigits: 2,
    minimumFractionDigits: 2,
  }).format(amount);
}

function formatRate(rate, lang) {
  if (!Number.isFinite(rate)) return "—";
  const locale = lang === "es" ? "es-MX" : "en-US";
  return (
    new Intl.NumberFormat(locale, {
      maximumFractionDigits: 4,
      minimumFractionDigits: 2,
    }).format(rate * 100) + " %"
  );
}

function translateStaticTexts() {
  const dict = uiText[currentLang];
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    const key = el.getAttribute("data-i18n");
    if (dict[key]) {
      el.textContent = dict[key];
    }
  });
}

function renderFormulaOptions() {
  const select = document.getElementById("formula-select");
  select.innerHTML = "";
  Object.values(formulas).forEach((formula) => {
    const option = document.createElement("option");
    option.value = formula.id;
    option.textContent = formula.names[currentLang];
    select.appendChild(option);
  });
}

function renderInputs(formulaId) {
  const container = document.getElementById("dynamic-inputs");
  container.innerHTML = "";
  const formula = formulas[formulaId];
  if (!formula) return;

  formula.inputs.forEach((field) => {
    const wrapper = document.createElement("div");
    wrapper.className = "field";

    const label = document.createElement("label");
    label.setAttribute("for", field.id);
    label.textContent = field.labels[currentLang];
    wrapper.appendChild(label);

    const input = document.createElement("input");
    input.type = "number";
    input.id = field.id;
    input.inputMode = "decimal";
    input.placeholder = field.placeholder[currentLang];
    wrapper.appendChild(input);

    const helper = document.createElement("div");
    helper.className = "helper";
    let helperText = "";
    if (field.type === "amount") {
      helperText =
        currentLang === "es" ? "Monto en unidades monetarias." : "Amount in money units.";
    } else if (field.type === "rate") {
      if (currentLang === "es") {
        helperText =
          currentPeriodMode === "yearly"
            ? "Introduce la TASA ANUAL nominal en porcentaje. Ej: 18."
            : "Introduce la tasa simple MENSUAL en porcentaje. Ej: 1.5.";
      } else {
        helperText =
          currentPeriodMode === "yearly"
            ? "Enter the NOMINAL ANNUAL rate as a percentage, e.g. 18."
            : "Enter the simple MONTHLY rate as a percentage, e.g. 1.5.";
      }
    } else if (field.type === "periods") {
      // Special case: formula that explicitly uses periods per year
      if (formula.id === "period_rate_from_annual") {
        helperText =
          currentLang === "es"
            ? "Número de periodos por año. Ej: 12 para meses."
            : "Number of periods per year. E.g. 12 for months.";
      } else if (currentPeriodMode === "yearly") {
        helperText =
          currentLang === "es"
            ? "Número de periodos en AÑOS."
            : "Number of periods in YEARS.";
      } else {
        helperText =
          currentLang === "es"
            ? "Número de periodos en MESES."
            : "Number of periods in MONTHS.";
      }
    }
    helper.textContent = helperText;
    wrapper.appendChild(helper);

    container.appendChild(wrapper);
  });

  const formulaText = document.getElementById("result-formula");
  formulaText.textContent = formula.symbol;

  const explanation = document.getElementById("result-explanation");
  explanation.textContent = formula.description[currentLang];
}

function parseInputs(formula) {
  const values = {};
  for (const field of formula.inputs) {
    const el = document.getElementById(field.id);
    if (!el) return { ok: false, data: null, error: "required" };
    const value = getNumberValue(el.value);
    if (!el.value || !Number.isFinite(value)) {
      return { ok: false, data: null, error: el.value ? "invalidNumber" : "required" };
    }
    if (field.type === "rate") {
      values[field.id] = value / 100;
    } else {
      values[field.id] = value;
    }
  }
  return { ok: true, data: values, error: null };
}

function handleSubmit(event) {
  event.preventDefault();
  const select = document.getElementById("formula-select");
  const formula = formulas[select.value];
  const errorEl = document.getElementById("error-message");
  errorEl.textContent = "";

  const parsed = parseInputs(formula);
  if (!parsed.ok) {
    const dict = uiText[currentLang].errors;
    errorEl.textContent = dict[parsed.error] || "";
    document.getElementById("result-value").textContent = "—";
    return;
  }

  const baseValues = parsed.data;
  const values = applyPeriodMode(formula, baseValues);

  if (formula.validate && !formula.validate(values)) {
    errorEl.textContent = uiText[currentLang].errors.negativeEffective;
    document.getElementById("result-value").textContent = "—";
    return;
  }

  const result = formula.compute(values);
  const display =
    formula.resultIsRate === true
      ? formatRate(result, currentLang)
      : formatCurrency(result, currentLang);

  const symbol = formula.resultSymbol || "";
  document.getElementById("result-value").textContent = `${symbol} = ${display}`;
}

function handleClear() {
  document
    .querySelectorAll("#dynamic-inputs input")
    .forEach((input) => (input.value = ""));
  document.getElementById("result-value").textContent = "—";
  document.getElementById("result-explanation").textContent = "";
  document.getElementById("result-formula").textContent = "";
  document.getElementById("error-message").textContent = "";
}

function setupLanguageSwitcher() {
  const buttons = document.querySelectorAll(".lang-button");
  buttons.forEach((btn) => {
    btn.addEventListener("click", () => {
      const lang = btn.getAttribute("data-lang");
      if (lang === currentLang) return;
      currentLang = lang;
      buttons.forEach((b) => {
        const active = b === btn;
        b.classList.toggle("active", active);
        b.setAttribute("aria-pressed", String(active));
      });
      translateStaticTexts();
      renderFormulaOptions();
      const select = document.getElementById("formula-select");
      const currentId = select.value || "future_value_simple";
      select.value = currentId;
      renderInputs(currentId);
    });
  });
}

function setupPeriodSwitcher() {
  const buttons = document.querySelectorAll(".period-button");
  if (!buttons.length) return;

  buttons.forEach((btn) => {
    btn.addEventListener("click", () => {
      const mode = btn.getAttribute("data-period");
      if (!mode || mode === currentPeriodMode) return;

      currentPeriodMode = mode;

      buttons.forEach((b) => {
        const active = b === btn;
        b.classList.toggle("active", active);
        b.setAttribute("aria-pressed", String(active));
      });

      // Re-render current formula inputs so helper texts match the mode
      const select = document.getElementById("formula-select");
      const currentId = select.value || "future_value_simple";
      select.value = currentId;
      renderInputs(currentId);
    });
  });
}

function applyPeriodMode(formula, values) {
  // Only adjust when user has chosen yearly mode
  if (currentPeriodMode !== "yearly" || !formula) {
    return values;
  }

  // Do not auto-convert for formulas that already handle this explicitly
  if (formula.id === "period_rate_from_annual" || formula.id === "simple_rate") {
    return values;
  }

  // Find a rate field and a periods field in the formula definition
  let rateFieldId = null;
  let periodsFieldId = null;
  if (Array.isArray(formula.inputs)) {
    formula.inputs.forEach((field) => {
      if (field.type === "rate" && !rateFieldId) rateFieldId = field.id;
      if (field.type === "periods" && !periodsFieldId) periodsFieldId = field.id;
    });
  }

  if (!rateFieldId || !periodsFieldId) {
    return values;
  }

  const rate = values[rateFieldId];
  const n = values[periodsFieldId];

  if (!Number.isFinite(rate) || !Number.isFinite(n)) {
    return values;
  }

  // Interpret entered rate as nominal ANNUAL and n as YEARS,
  // and convert to equivalent monthly simple interest parameters.
  const adjusted = { ...values };
  adjusted[rateFieldId] = rate / MONTHS_PER_YEAR;
  adjusted[periodsFieldId] = n * MONTHS_PER_YEAR;

  return adjusted;
}

function init() {
  translateStaticTexts();
  renderFormulaOptions();

  const select = document.getElementById("formula-select");
  const initialId = select.value || "future_value_simple";
  select.value = initialId;
  renderInputs(initialId);

  select.addEventListener("change", () => renderInputs(select.value));
  document
    .getElementById("calculator-form")
    .addEventListener("submit", handleSubmit);
  document
    .getElementById("clear-button")
    .addEventListener("click", handleClear);

  setupLanguageSwitcher();
  setupPeriodSwitcher();
}

document.addEventListener("DOMContentLoaded", init);

